config/routes.rb
Rails.application.routes.draw do

  get "/tasks", to: "tasks#index", as: :tasks

  get "/tasks/new", to: "tasks#new", as: :new_list

  post "tasks", to: "tasks#create"

  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit

  patch "/tasks/:id", to: "tasks#update", as: :task

  delete "/tasks/:id", to: "tasks#destroy"

  get "/tasks/:id", to: "tasks#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end
  
  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/destroy.html.erb
<h1>Delete a task</h1>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control"%>
  <%= f.label :details %>
  <%= f.text_area :details, class:"form-control"%>
  <%= f.submit :Submit, class:"btn btn-success"%>
  <%= f.check_box :completed%>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ol>
<% @tasks.each do |task| %>

  <li> <%= link_to task.title, task_path(task) %> </li>

    <% if task.completed? %>
        <i class="fa-solid fa-square-check"></i>
        <% else  %>
        <i class="fa-solid fa-battery-empty"></i>
      <% end %>
  <% end %>
</ol>

<%= link_to "Add a new task ➡️📝", new_list_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control"%>
  <%= f.label :details %>
  <%= f.text_area :details, class:"form-control"%>
  @<%= f.submit :Submit, class:"btn btn-success"%>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h3><%= @task.details %></h3>

<h4><%= link_to "Edit this list", task_edit_path %></h4>

<h4><%= link_to "Delete this list", task_path(@task), data: { turbo_method: :delete, turbo_confirm: "delete #{@task.title}???"} %></h4>

<h4><%= link_to "Back to list", tasks_path %></h4>